# Generated by Django 2.1.5 on 2019-03-13 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='ФИО ')),
                ('brand', models.CharField(max_length=10000, verbose_name='Инфо о пациенте ')),
                ('date', models.DateField(verbose_name='Дата записи ')),
                ('time', models.CharField(max_length=5, verbose_name='Время  ')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='ФИО')),
                ('info', models.CharField(max_length=10000, verbose_name='Инфо о специалисте')),
            ],
            options={
                'verbose_name': 'Специалист',
                'verbose_name_plural': 'Специалисты',
            },
        ),
        migrations.AddField(
            model_name='recording',
            name='specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.Specialist', verbose_name='Доктор '),
        ),
    ]
